Update trivy-pipelines.yml

diff --git a/tfsec/trivy-pipelines.yml b/tfsec/trivy-pipelines.yml
--- a/tfsec/trivy-pipelines.yml
+++ b/tfsec/trivy-pipelines.yml
@@ -8,7 +8,9 @@ steps:
 - script: |
     #echo "AVD-AZU-0047" > .trivyignore
     mkdir ${{parameters.WorkingDirectory}}/TrivyReport
-    docker run --rm -v ${{parameters.WorkingDirectory}}:/src aquasec/trivy config ./ || exit 1
+    echo "Before running command"
+    docker run --rm -v ${{parameters.WorkingDirectory}}:/src aquasec/trivy config ./ || (echo "Command failed" && exit 1)
+    echo "After running command"
   displayName: 'Run Trivy Vulnerability Scan'
 - script: |
     docker run --rm -v ${{parameters.WorkingDirectory}}:/src aquasec/trivy config ./ --format json > ${{parameters.WorkingDirectory}}/TrivyReport/Trivy-Report.json || exit 1
