Update trivy-pipelines.yml

diff --git a/tfsec/trivy-pipelines.yml b/tfsec/trivy-pipelines.yml
--- a/tfsec/trivy-pipelines.yml
+++ b/tfsec/trivy-pipelines.yml
@@ -1,20 +1,40 @@
 parameters:
 - name: WorkingDirectory
   default: $(System.DefaultWorkingDirectory)
-  
+- name: TrivyIgnore
+  default: |
+    #AVD-AZU-0047
+    
 steps:
-- checkout: self
+- script: echo "Starting Trivy Scan Pipeline"
+  displayName: 'Initialising Trivy'
 - script: |
-    mkdir ${{parameters.WorkingDirectory}}/TrivyReport
-    docker run --rm -v ${{parameters.WorkingDirectory}}:/src aquasec/trivy config ./ --exit-code 1 --severity HIGH,CRITICAL
-  displayName: 'Run Trivy Vulnerability Scan'
+    docker pull aquasec/trivy
+  displayName: 'Pull Trivy Image'
 - script: |
-    docker run --rm -v ${{parameters.WorkingDirectory}}:/src aquasec/trivy config ./ --format json > ${{parameters.WorkingDirectory}}/TrivyReport/Trivy-Report.json
-  displayName: 'Generate Trivy JSON Report'
+   echo "${{parameters.TrivyIgnore}}" > ${{parameters.WorkingDirectory}}/.trivyignore
+  displayName: 'Create .trivyignore'
+- script: |
+    echo "Listing files in the working directory"
+    ls -la ${{parameters.WorkingDirectory}}/Terraform
+  displayName: 'List Files in Working Directory'
+- script: |
+    docker run --rm -v ${{parameters.WorkingDirectory}}:/src -w /src aquasec/trivy config ./ --exit-code 1 --severity HIGH,CRITICAL --ignorefile .trivyignore
+  displayName: 'Run Trivy Scan'
+  continueOnError: true
+- script: |
+    docker run --rm -v ${{parameters.WorkingDirectory}}:/src -w /src aquasec/trivy config ./ --format json --ignorefile .trivyignore > ${{parameters.WorkingDirectory}}/TrivyReport.json
+  displayName: 'Run Trivy Scan Publish JSON Report'
 - task: PublishBuildArtifacts@1
-  displayName: Publish Trivy JSON Report
   inputs:
-    PathtoPublish: '${{parameters.WorkingDirectory}}/TrivyReport' 
+    PathtoPublish: '${{parameters.WorkingDirectory}}/TrivyReport.json'
     ArtifactName: 'TrivyReport'
-    failTaskOnFailedTests: true
-    publishRunAttachments: true
+    publishLocation: 'Container'
+  condition: succeededOrFailed()
+  displayName: 'Publish Trivy JSON Report'
+- script: |
+    if grep -q "HIGH\|CRITICAL" ${{parameters.WorkingDirectory}}/TrivyReport.json; then
+      echo "Misconfigurations found. Failing the pipeline."
+      exit 1
+    fi
+  displayName: 'Fail pipeline if misconfigurations found'
