Update trivy-new-pipeline.yml

diff --git a/tfsec/trivy-new-pipeline.yml b/tfsec/trivy-new-pipeline.yml
--- a/tfsec/trivy-new-pipeline.yml
+++ b/tfsec/trivy-new-pipeline.yml
@@ -1,11 +1,11 @@
+###JUNIT WORKING###
 parameters:
 - name: WorkingDirectory
   default: $(System.DefaultWorkingDirectory)
 - name: TrivyIgnore
   default: |
     #AVD-AZU-0047
-    #AVD-AZU-0011
-
+    
 steps:
 - script: echo "Starting Trivy Scan Pipeline"
   displayName: 'Initialising Trivy'
@@ -16,37 +16,38 @@ steps:
    echo "${{parameters.TrivyIgnore}}" > ${{parameters.WorkingDirectory}}/.trivyignore
   displayName: 'Create .trivyignore'
 - script: |
-    echo "Listing files in the working directory"
-    ls -la ${{parameters.WorkingDirectory}}/Terraform
-  displayName: 'List Files in Working Directory'
+    cat ${{parameters.WorkingDirectory}}/.trivyignore
+  displayName: 'Print .trivyignore'
+- script: |
+    wget -O ${{parameters.WorkingDirectory}}/junit.tpl https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/junit.tpl
+  displayName: 'Download junit.tpl'
 - script: |
     docker run --rm -v ${{parameters.WorkingDirectory}}:/src -w /src aquasec/trivy config ./ --exit-code 1 --severity HIGH,CRITICAL --ignorefile .trivyignore
   displayName: 'Run Trivy Scan'
   continueOnError: true
 - script: |
-    docker run --rm -v ${{parameters.WorkingDirectory}}:/src -w /src aquasec/trivy config ./ --format json --ignorefile .trivyignore > ${{parameters.WorkingDirectory}}/TrivyReport.json
-  displayName: 'Run Trivy Scan Publish JSON Report'
-- task: PublishBuildArtifacts@1
+    docker run --rm -v ${{parameters.WorkingDirectory}}:/src -w /src aquasec/trivy config ./ --severity HIGH,CRITICAL --ignorefile .trivyignore --format template --template "@/src/junit.tpl" -o /src/TrivyReport.xml
+  displayName: 'Run Trivy Scan Publish Tests'
+- task: PublishTestResults@2
   inputs:
-    PathtoPublish: '${{parameters.WorkingDirectory}}/TrivyReport.json'
-    ArtifactName: 'TrivyReport'
-    publishLocation: 'Container'
-  condition: succeededOrFailed()
-  displayName: 'Publish Trivy JSON Report'
-- script: |
-    if grep -q "HIGH\|CRITICAL" ${{parameters.WorkingDirectory}}/TrivyReport.json; then
-      echo "Misconfigurations found. Failing the pipeline."
-      exit 1
-    fi
-  displayName: 'Fail pipeline if misconfigurations found'
+    testResultsFormat: 'JUnit'
+    testResultsFiles: '${{parameters.WorkingDirectory}}/TrivyReport.xml'
+    searchFolder: '${{parameters.WorkingDirectory}}/'
+    testRunTitle: 'Trivy Scan'
+    mergeTestResults: true
+    failTaskOnFailedTests: true
+    #publishRunAttachments: true
+  condition: 'always()'
 
+###WORKING###
 #parameters:
 #- name: WorkingDirectory
 #  default: $(System.DefaultWorkingDirectory)
 #- name: TrivyIgnore
 #  default: |
-#    AVD-AZU-0047
-#    
+#    #AVD-AZU-0047
+#    #AVD-AZU-0011
+#
 #steps:
 #- script: echo "Starting Trivy Scan Pipeline"
 #  displayName: 'Initialising Trivy'
@@ -57,25 +58,26 @@ steps:
 #   echo "${{parameters.TrivyIgnore}}" > ${{parameters.WorkingDirectory}}/.trivyignore
 #  displayName: 'Create .trivyignore'
 #- script: |
-#    cat ${{parameters.WorkingDirectory}}/.trivyignore
-#  displayName: 'Print .trivyignore'
-#- script: |
-#    wget -O ${{parameters.WorkingDirectory}}/junit.tpl https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/junit.tpl
-#  displayName: 'Download junit.tpl'
+#    echo "Listing files in the working directory"
+#    ls -la ${{parameters.WorkingDirectory}}/Terraform
+#  displayName: 'List Files in Working Directory'
 #- script: |
 #    docker run --rm -v ${{parameters.WorkingDirectory}}:/src -w /src aquasec/trivy config ./ --exit-code 1 --severity HIGH,CRITICAL --ignorefile .trivyignore
 #  displayName: 'Run Trivy Scan'
 #  continueOnError: true
 #- script: |
-#    docker run --rm -v ${{parameters.WorkingDirectory}}:/src -w /src aquasec/trivy config ./ --severity HIGH,CRITICAL --ignorefile .trivyignore --format template --template "@/src/junit.tpl" -o /src/TrivyReport.xml
-#  displayName: 'Run Trivy Scan Publish Tests'
-#- task: PublishTestResults@2
+#    docker run --rm -v ${{parameters.WorkingDirectory}}:/src -w /src aquasec/trivy config ./ --format json --ignorefile .trivyignore > ${{parameters.WorkingDirectory}}/TrivyReport.json
+#  displayName: 'Run Trivy Scan Publish JSON Report'
+#- task: PublishBuildArtifacts@1
 #  inputs:
-#    testResultsFormat: 'JUnit'
-#    testResultsFiles: '${{parameters.WorkingDirectory}}/TrivyReport.xml'
-#    searchFolder: '${{parameters.WorkingDirectory}}/'
-#    testRunTitle: 'Trivy Scan'
-#    mergeTestResults: true
-#    failTaskOnFailedTests: true
-#    #publishRunAttachments: true
-#  condition: 'always()'
+#    PathtoPublish: '${{parameters.WorkingDirectory}}/TrivyReport.json'
+#    ArtifactName: 'TrivyReport'
+#    publishLocation: 'Container'
+#  condition: succeededOrFailed()
+#  displayName: 'Publish Trivy JSON Report'
+#- script: |
+#    if grep -q "HIGH\|CRITICAL" ${{parameters.WorkingDirectory}}/TrivyReport.json; then
+#      echo "Misconfigurations found. Failing the pipeline."
+#      exit 1
+#    fi
+#  displayName: 'Fail pipeline if misconfigurations found'
