Update trivy-new-pipeline.yml

diff --git a/tfsec/trivy-new-pipeline.yml b/tfsec/trivy-new-pipeline.yml
--- a/tfsec/trivy-new-pipeline.yml
+++ b/tfsec/trivy-new-pipeline.yml
@@ -15,9 +15,6 @@ steps:
 - script: |
    echo "${{parameters.TrivyIgnore}}" > ${{parameters.WorkingDirectory}}/.trivyignore
   displayName: 'Create .trivyignore'
-#- script: |
-#    cat ${{parameters.WorkingDirectory}}/.trivyignore
-#  displayName: 'Print .trivyignore'
 - script: |
     docker run --rm -v ${{parameters.WorkingDirectory}}:/src -w /src aquasec/trivy config ./ --exit-code 1 --severity HIGH,CRITICAL --ignorefile .trivyignore
   displayName: 'Run Trivy Scan'
@@ -25,9 +22,6 @@ steps:
 - script: |
     docker run --rm -v ${{parameters.WorkingDirectory}}:/src -w /src aquasec/trivy config ./ --format json --ignorefile .trivyignore > ${{parameters.WorkingDirectory}}/TrivyReport.json
   displayName: 'Run Trivy Scan Publish JSON Report'
-#- script: |
-#    ls -la ${{parameters.WorkingDirectory}}
-#  displayName: 'List files in working directory'
 - task: PublishBuildArtifacts@1
   inputs:
     PathtoPublish: '${{parameters.WorkingDirectory}}/TrivyReport.json'
@@ -35,12 +29,12 @@ steps:
     publishLocation: 'Container'
   condition: succeededOrFailed()
   displayName: 'Publish Trivy JSON Report'
-- script: |
-    if grep -q "HIGH\|CRITICAL" ${{parameters.WorkingDirectory}}/TrivyReport.json; then
-      echo "Misconfigurations found. Failing the pipeline."
-      exit 1
-    fi
-  displayName: 'Fail pipeline if misconfigurations found'
+#- script: |
+#    if grep -q "HIGH\|CRITICAL" ${{parameters.WorkingDirectory}}/TrivyReport.json; then
+#      echo "Misconfigurations found. Failing the pipeline."
+#      exit 1
+#    fi
+#  displayName: 'Fail pipeline if misconfigurations found'
 
 #| tee ${{parameters.WorkingDirectory}}/TrivyReport.json
 #parameters:
